### ISSUE TITLE
Failure to parse file with advanced CSS features

### ISSUE THREAD

**Issue by rosteen** [Kozea/cssselect2#14]
I am attempting to use `svglib` to parse an SVG file output by `bqplot`, and am hitting an error in `cssselect2`. It seems that the SVG file uses some advanced CSS features, like CSS variables. I initially filed [an issue in the svglib repository](https://github.com/deeplook/svglib/issues/248), but it seems the problem may be here - does cssselect2 not support some features used in this file, or is this a bug that can be fixed? The error trace is reproduced below, and the file in question is attached. Thanks in advance for any insight you can provide.

```
>>> from svglib.svglib import svg2rlg
>>> drawing = svg2rlg("chrome_test2.svg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/svglib/svglib.py", line 1423, in svg2rlg
    drawing = svgRenderer.render(svg_root)
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/svglib/svglib.py", line 574, in render
    main_group = self.renderSvg(node, outermost=True)
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/svglib/svglib.py", line 831, in renderSvg
    self.renderG(NodeTracker(def_node))
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/svglib/svglib.py", line 869, in renderG
    item = self.renderNode(child, parent=gr)
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/svglib/svglib.py", line 609, in renderNode
    self.renderStyle(n)
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/svglib/svglib.py", line 879, in renderStyle
    self.attrConverter.css_rules = CSSMatcher(node.text)
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/svglib/svglib.py", line 157, in __init__
    selectors = cssselect2.compile_selector_list(rule.prelude)
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/compiler.py", line 30, in compile_selector_list
    return [
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/compiler.py", line 30, in <listcomp>
    return [
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/parser.py", line 28, in parse
    yield parse_selector(tokens, namespaces)
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/parser.py", line 50, in parse_selector
    return Selector(result, pseudo_element)
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/parser.py", line 291, in __init__
    self.specificity = tree.specificity
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/parser.py", line 333, in specificity
    return tuple(map(sum, zip(
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/parser.py", line 334, in <genexpr>
    *(sel.specificity for sel in self.simple_selectors))))
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/parser.py", line 333, in specificity
    return tuple(map(sum, zip(
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/cssselect2/parser.py", line 334, in <genexpr>
    *(sel.specificity for sel in self.simple_selectors))))
AttributeError: 'NoneType' object has no attribute 'specificity'
```

[chrome_test2.svg.txt](https://github.com/Kozea/cssselect2/files/4984174/chrome_test2.svg.txt)

**Comment by liZe** [comment]
Hello,

Thanks a lot for this bug report! The problem is caused by the empty `:not()` selector, I have to fix this.

**Comment by rosteen** [comment]
Thanks for your quick attention on this, I'm glad it was an easy fix!

**Comment by liZe** [comment]
This issue is fixed, but svglib keeps on crashing because you have to catch bad selectors (and `:not()` is a bad selector).

**Comment by rosteen** [comment]
Ahh, good to know - I was about to go test, I'll continue working on resolving that then.

**Comment by liZe** [comment]
I’ll release a new version in a few weeks, I have to clean packaging stuff before.
